#!/usr/bin/env python3
"""Cross-cell digest of the D2 grid (scripts/d2/README.md), for the written summary.

    .venv/bin/python scripts/d2/digest_d2.py

Reads results/d2/{l1,l2}_grid.csv and the *_summary.csv files written by summarise_d2.py, and
writes results/d2/d2_digest.md: convergence by design, coverage by scenario, and the rates at
which 90% intervals exclude zero or clear the placeholder thresholds. Means are taken over the
cells named in each table's index; every number in results/d2/SUMMARY.md comes from this file.
"""
from __future__ import annotations

from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
D2 = ROOT / "results" / "d2"


def block(title: str, frame: pd.DataFrame | pd.Series) -> str:
    return f"## {title}\n\n```\n{frame.round(3).to_string()}\n```\n"


def main():
    out = ["# D2 digest\n<!-- SUMMARY: generated by scripts/d2/digest_d2.py from results/d2/*_grid.csv "
           "and *_grid_summary.csv; cross-cell tables behind SUMMARY.md -->\n"]

    raw = pd.read_csv(D2 / "l1_grid.csv")
    mc = raw[raw.design.isin(["b10", "b30", "c"])].copy()
    mc["cov90"] = (mc.truth >= mc.q05) & (mc.truth <= mc.q95)
    mc["rhat_over_1.01"] = mc.rhat_max > 1.01
    out.append(block("L1: largest R-hat and smallest ESS per fit, by design (MCMC designs only)",
                     mc.drop_duplicates(["cell", "design", "rep"]).groupby("design").agg(
                         fits=("rhat_max", "size"),
                         rhat_median=("rhat_max", "median"),
                         rhat_q90=("rhat_max", lambda x: x.quantile(.9)),
                         rhat_max=("rhat_max", "max"),
                         share_over_1_05=("rhat_max", lambda x: (x > 1.05).mean()),
                         ess_q10=("ess_min", lambda x: x.quantile(.1)),
                         share_with_divergences=("divergences", lambda x: (x > 0).mean()))))
    out.append(block("L1: 90% coverage against `truth`, fits with largest R-hat above vs at most 1.01",
                     mc[mc.estimand != "gamma"].groupby(["design", "estimand", "rhat_over_1.01"])
                     .cov90.mean().unstack()))

    s1 = pd.read_csv(D2 / "l1_grid_summary.csv")
    s1 = s1[s1.estimand != "gamma"]
    out.append(block("L1: 90% coverage (summariser's cover90), mean over cells, by scenario",
                     s1.pivot_table(index="kind", columns=["design", "estimand"], values="cover90",
                                    aggfunc="mean")))
    core1 = s1[s1.kind == "core"]
    out.append(block("L1 core: share of fits whose 90% interval excludes 0, by true beta",
                     core1.pivot_table(index=["design", "estimand"], columns="beta", values="excl0",
                                       aggfunc="mean")))
    out.append(block("L1 core: 90% coverage by number of pairs N",
                     core1.pivot_table(index=["design", "estimand"], columns="N", values="cover90",
                                       aggfunc="mean")))

    s2 = pd.read_csv(D2 / "l2_grid_summary.csv")
    out.append(block("L2: 90% coverage, mean over cells, by scenario",
                     s2.pivot_table(index="kind", columns=["fit", "estimand"], values="cover90",
                                    aggfunc="mean")))
    z = s2[s2.estimand == "apc_z"]
    out.append(block("L2, apc_z: share of fits whose 90% interval excludes 0",
                     z.pivot_table(index=["kind", "fit"], columns=["story", "beta_z"], values="excl0",
                                   aggfunc="mean")))
    out.append(block("L2, apc_z: share of fits in 'support' (90% interval wholly beyond the placeholder "
                     "threshold, .03, in the predicted direction)",
                     z.pivot_table(index=["kind", "fit"], columns=["story", "beta_z"], values="support",
                                   aggfunc="mean")))
    out.append(block("L2: convergence (share of fits per cell)",
                     s2[["rhat>1.01", "div>0"]].describe().loc[["mean", "50%", "max"]]))

    (D2 / "d2_digest.md").write_text("\n".join(out))
    print(f"wrote {D2 / 'd2_digest.md'}")


if __name__ == "__main__":
    main()
