#!/usr/bin/env python3
"""Summarise D2 fits (scripts/d2/README.md, "Reported, per estimand and cell").

    .venv/bin/python scripts/d2/summarise_d2.py results/d2/l1_grid.csv
    .venv/bin/python scripts/d2/summarise_d2.py results/d2/l2_grid.csv

Writes <input stem>_summary.csv and .md beside the input. Placeholder decision thresholds
are the README's: theta .05/.10/.20 (L1), average predictive comparison .03 (L2, where the
rarity account predicts a negative value).
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd

L1_T = (0.05, 0.10, 0.20)
L2_T = 0.03


def mcse(p: float, n: int) -> float:
    return float(np.sqrt(p * (1 - p) / n)) if n else np.nan


def summarise(df: pd.DataFrame) -> pd.DataFrame:
    part = df["part"].iloc[0]
    keys = (["cell", "kind", "N", "s_off", "beta", "design", "estimand"] if part == "L1"
            else ["cell", "kind", "K", "rho_zs", "beta_z", "story", "fit", "estimand"])
    out = []
    for k, g in df.groupby(keys, dropna=False, sort=True):
        row = dict(zip(keys, k))
        n = len(g)
        row["n"] = n
        t = g["truth"]
        has_t = t.notna().all()
        row["truth"] = float(t.mean()) if has_t else np.nan
        if "truth_pool" in g and g["truth_pool"].notna().any():
            row["truth_pool"] = float(g["truth_pool"].mean())
        if "truth_coder" in g and g["truth_coder"].notna().any():
            row["truth_coder"] = float(g["truth_coder"].mean())
        if has_t:
            c90 = ((g["q05"] <= t) & (t <= g["q95"])).mean()
            row["cover90"], row["mcse90"] = c90, mcse(c90, n)
            if g["q25"].notna().all():
                c50 = ((g["q25"] <= t) & (t <= g["q75"])).mean()
                row["cover50"], row["mcse50"] = c50, mcse(c50, n)
            row["bias"] = float((g["mean"] - t).mean())
            row["rmse"] = float(np.sqrt(((g["mean"] - t) ** 2).mean()))
        row["width90"] = float((g["q95"] - g["q05"]).median())
        excl = (g["q05"] > 0) | (g["q95"] < 0)
        row["excl0"] = float(excl.mean())
        if has_t and abs(row["truth"]) > 1e-9 and excl.any():
            e = g[excl]
            row["typeS"] = float((np.sign(e["mean"]) != np.sign(row["truth"])).mean())
            row["typeM"] = float((e["mean"].abs() / abs(row["truth"])).mean())
        est = row["estimand"]
        if part == "L1" and est in ("theta", "theta_m"):
            for T in L1_T:
                row[f"support@{T}"] = float((g["q05"] > T).mean())
                row[f"against@{T}"] = float((g["q95"] < T).mean())
        if part == "L2" and est == "apc_z":
            row["support"] = float((g["q95"] < -L2_T).mean())
            row["against"] = float((g["q05"] > -L2_T).mean())
        if "tip" in g and g["tip"].notna().any():
            tip = g["tip"].replace(np.inf, np.nan)
            row["tip_share_excl0"] = float(g["tip"].notna().mean())
            row["tip_median"] = float(tip.median()) if tip.notna().any() else np.nan
        if "rhat_max" in g and g["rhat_max"].notna().any():
            row["rhat>1.01"] = float((g["rhat_max"] > 1.01).mean())
            row["div>0"] = float((g["divergences"] > 0).mean())
            row["sec_median"] = float(g["seconds"].median())
        out.append(row)
    return pd.DataFrame(out)


def to_md(s: pd.DataFrame) -> str:
    cols = [c for c in s.columns if s[c].notna().any()]
    fmt = lambda x: "" if (isinstance(x, float) and np.isnan(x)) else (f"{x:.3f}" if isinstance(x, float) else str(x))  # noqa: E731
    lines = ["| " + " | ".join(cols) + " |", "|" + "---|" * len(cols)]
    for _, r in s[cols].iterrows():
        lines.append("| " + " | ".join(fmt(r[c]) for c in cols) + " |")
    return "\n".join(lines)


def main():
    src = Path(sys.argv[1])
    df = pd.read_csv(src)
    s = summarise(df)
    s.to_csv(src.with_name(src.stem + "_summary.csv"), index=False)
    head = (f"# D2 summary: {src.name}\n<!-- SUMMARY: generated by scripts/d2/summarise_d2.py from {src.name}; "
            f"simulated data, design evaluation only · status: generated -->\n\n"
            "Coverage with Monte Carlo SEs; Type S and M among fits whose 90% interval excludes 0, non-null truths "
            "only; decision shares at the README's placeholder thresholds.\n\n")
    src.with_name(src.stem + "_summary.md").write_text(head + to_md(s) + "\n")
    print(to_md(s))


if __name__ == "__main__":
    main()
