#!/usr/bin/env python3
"""Render results/strandA/SUMMARY.md from the strand A CSVs, so every number
in the summary comes from the results files rather than being retyped."""
from __future__ import annotations

from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
R = ROOT / "results" / "strandA"


def md(df: pd.DataFrame, index: bool = True) -> str:
    """Minimal Markdown table (avoids a tabulate dependency)."""
    d = df.reset_index() if index else df
    cols = [" / ".join(map(str, c)) if isinstance(c, tuple) else str(c) for c in d.columns]
    fmt = lambda v: f"{v:.3f}" if isinstance(v, float) else str(v)
    lines = ["| " + " | ".join(cols) + " |", "|" + "---|" * len(cols)]
    lines += ["| " + " | ".join(fmt(v) for v in row) + " |" for row in d.itertuples(index=False)]
    return "\n".join(lines)


def table(df: pd.DataFrame, digits: int = 3) -> str:
    return md(df.round(digits))


def null_lr1(pi, n1=100, n0=900):
    """Exact E[LR1] with no group difference: a ~ Bin(n1, pi), b ~ Bin(n0, pi)."""
    import numpy as np
    from scipy.stats import binom
    a, b = np.arange(n1 + 1), np.arange(n0 + 1)
    return float(np.sum(binom.pmf(a, n1, pi) * (a + .5) / (n1 + 1)) *
                 np.sum(binom.pmf(b, n0, pi) * (n0 + 1) / (b + .5)))


def pivot(df, metric, index="pi_neg", columns=None, value="mean"):
    sub = df[df.metric == metric]
    if columns is None:
        return sub.set_index(index)[[value]].rename(columns={value: metric})
    return sub.pivot_table(index=index, columns=columns, values=value)


def main():
    out = ["# Strand A results", "",
           "<!-- SUMMARY: Generated by scripts/simulation/summarise_strand_a.py from the CSVs in this folder; do not edit by hand · status: generated -->",
           "", "Spec: `scripts/simulation/README.md` (committed before the first run). "
           "Post-run changes: `DECISIONS.md`, 2026-10-07. Run logs: `logs/strandA-*.json`.", ""]

    rep = pd.read_csv(R / "replicate.csv")
    chk = pd.read_csv(R / "check_against_paper.csv")
    out += ["## 1. Replication of UWA's design", "",
            "1,000 runs per condition; K = 10 groups of 100; 50 positive and 50 negative attributes.", ""]
    cols = ["share_negative_top5", "mean_p_A_given_G1_top5", "LR1_neg_rank1", "LR1_pos_rank1"]
    out += [table(rep[rep.metric.isin(cols)].pivot_table(index="pi_neg", columns="metric", values="mean")[cols]), ""]
    out += ["Checks against the paper (T1 to T5 from its text; the rest against values read from Figure 6 by eye):", "",
            md(chk, index=False), ""]
    if (R / "replicate_seeds.csv").exists():
        rs = pd.read_csv(R / "replicate_seeds.csv")
        rs = rs[rs.metric.isin(cols)].set_index(["pi_neg", "metric"])
        rs["committed_seed"] = rep.set_index(["pi_neg", "metric"])["mean"]
        rs["z"] = (rs["committed_seed"] - rs["mean_across_seeds"]) / rs["sd_across_seeds"]
        out += ["Committed seed against 50 other seeds per condition:", "",
                table(rs[["mean_across_seeds", "sd_across_seeds", "committed_seed", "z"]]), ""]
    if (R / "ties.csv").exists():
        ties = pd.read_csv(R / "ties.csv")
        base = rep.set_index(["pi_neg", "metric"])["mean"]
        gaps = {m: float((ties[ties.ties == m].set_index(["pi_neg", "metric"])["mean"] - base).abs().max())
                for m in ("pos_first", "neg_first")}
        out += [f"Tie rules on the same draws: largest absolute difference from random tie-breaking, "
                f"positives-first {gaps['pos_first']:.4f}, negatives-first {gaps['neg_first']:.4f}.", ""]

    fr = pd.read_csv(R / "fresh.csv")
    fcols = ["original_ppv_top5", "fresh_ppv_top5", "mean_p_A_given_G1_top5",
             "fresh_p_A_given_G1_top5", "mean_pi_top5", "fresh_LR1_top5"]
    out += ["## 2. Fresh-sample check", "",
            "The top-5 attributes chosen in one sample, re-measured in an independent sample from the same "
            "population (no true group differences). Expected: PPV at p(G1) = .10, p(A|G1) at the base rate, "
            "LR near 1 (Jeffreys smoothing biases it slightly upward at small counts).", "",
            table(fr.pivot_table(index="pi_neg", columns="metric", values="mean")[fcols]
                  .assign(null_LR1_unselected=lambda d: [null_lr1(p) for p in d.index])), "",
            "`null_LR1_unselected` is the exact expected smoothed LR for an attribute with no group difference "
            "and no selection step, i.e. the bias Jeffreys smoothing alone produces at that base rate. "
            "The fresh LRs match it, so the selected attributes carry no leftover signal.", ""]

    dv = pd.read_csv(R / "diversity.csv")
    out += ["## 3. Negativity diversity (50 positive, 100 negative)", "",
            table(pd.concat([
                rep[rep.metric.isin(cols)].pivot_table(index="pi_neg", columns="metric", values="mean")[cols].add_suffix(" (50/50)"),
                dv[dv.metric.isin(cols)].pivot_table(index="pi_neg", columns="metric", values="mean")[cols].add_suffix(" (50/100)"),
            ], axis=1).sort_index(axis=1)), ""]

    gs = pd.read_csv(R / "groupsize.csv")
    out += ["## 4. A5: unequal group sizes (total N = 1,000; target size varied)", "",
            "Reading: the share negative barely moves with target size, but chance stereotypes of small groups "
            "look more diagnostic (higher LR) and more descriptive (higher p(A|G1)) in-sample, because the "
            "sampling noise in p(A|G1) scales as 1/sqrt(n1). The fresh PPV equals p(G1) at every size: "
            "none of it replicates. A modulation of UWA's no-minority-assumption claim, from sample size, "
            "not a finding about minorities as such.", ""]
    for m in ("share_negative_top5", "mean_p_A_given_G1_top5", "LR1_neg_rank1", "original_ppv_top5", "fresh_ppv_top5"):
        out += [f"**{m}** (rows: target size; columns: π_neg)", "",
                table(gs[gs.metric == m].pivot_table(index="n_target", columns="pi_neg", values="mean")), ""]

    if (R / "consensus_check.csv").exists():
        cc = pd.read_csv(R / "consensus_check.csv")
        out += ["## 5. Consensus split", "",
                "Approximation check (shared society, M = 1,000, n = 30, .70/.30, δ = 0): mean pairwise Jaccard",
                "", md(cc[["method", "mean", "mc_se", "runs"]], index=False), ""]
    if (R / "consensus.csv").exists():
        cs = pd.read_csv(R / "consensus.csv")
        cs["society_M"] = cs["society_M"].fillna(0).astype(int).astype(str).replace("0", "-")
        chance = cs["chance_jaccard"].iloc[0]
        from scipy.stats import hypergeom
        import numpy as np
        rv, x = hypergeom(50, 5, 5), np.arange(6)
        chance50 = float(np.sum(rv.pmf(x) * x / (10 - x)))
        out += [f"Chance Jaccard for two random 5-of-100 sets: {chance:.4f}; for two random 5-of-50 sets "
                f"(the relevant baseline when every perceiver's top 5 is negative, as at π_neg ≤ .2): {chance50:.4f}.", ""]
        null = cs[cs.delta == 0]
        for m in ("jaccard_mean_pairwise", "share_negative_mean", "share_negative_sd_across_perceivers",
                  "jaccard_with_society_top5"):
            sub = null[null.metric == m]
            if len(sub):
                out += [f"**{m}, no true differences (δ = 0)** (rows: version, society size M, n per group; columns: π_neg)", "",
                        table(sub.pivot_table(index=["version", "society_M", "n_per_group"], columns="pi_neg", values="mean")), ""]
        out += ["Reading the δ tables: \"negative\" and \"positive\" here are labels on two base rates "
                "(π = .30 and .70 at .70/.30). True differences on the rare attributes are picked up far more "
                "readily than on the common ones, because rarity raises the PPV ceiling (UWA's Equation 3). "
                "In UWA's ecology rare means negative; the design can't separate valence from rarity.", ""]
        for m in ("jaccard_mean_pairwise", "hit_rate_true_differences"):
            sub = cs[(cs.metric == m) & (cs.pi_neg == 0.3)]
            out += [f"**{m} at .70/.30 by true difference δ** (rows: version, M, n, valence of the differing attributes; columns: δ)", "",
                    table(sub.pivot_table(index=["version", "society_M", "n_per_group", "diff_valence"], columns="delta", values="mean")), ""]
    if (R / "consensus_equal_shift.csv").exists():
        es = pd.read_csv(R / "consensus_equal_shift.csv")
        out += ["**Post hoc, exploratory: equal absolute shift.** Added 2026-10-07 after the consensus run, to test "
                "whether the asymmetry depended on the logit scale, which moves rates near .30 more than rates near .70. "
                "(.70/.30, independent version, n = 100; "
                "rows: valence of the differing attributes; columns: shift added to the target group's rate)", ""]
        for m in ("jaccard_mean_pairwise", "hit_rate_true_differences"):
            out += [f"*{m}*", "", table(es[es.metric == m].pivot_table(index="diff_valence", columns="abs_shift", values="mean")), ""]
    (R / "SUMMARY.md").write_text("\n".join(out))
    print("wrote", (R / "SUMMARY.md").relative_to(ROOT))


if __name__ == "__main__":
    main()
